server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

portfolio-app:
  jobs:
    nbp:
      enabled: true
    metal-api:
      enabled: false
    coin-paprica:
      enabled: true