server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:portfolio
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/currency
  #    username: postgres
  #    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        :web-allow-others: false

portfolio-app:
  jobs:
    nbp:
      enabled: true
    metal-api:
      enabled: false
    coin-paprica:
      enabled: true